
server:
  port: 9999

magic-api:

  #配置web页面入口
  web: /magic/web

  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: /Users/admin/charming/magicapi-resource

  security-config:
    username: root # 登录用的用户名
    password: root # 登录用的密码
#
#  response-code:
#    success: 200 #执行成功的code值
#    invalid: 400 #参数验证未通过的code值
#    exception: 500 #执行出现异常的code值
#
#  response: |- #配置JSON格式，格式为magic-script中的表达式
#    {
#      code: code,
#      message: message,
#      data,
#      timestamp,
#      requestTime,
#      executeTime,
#    }

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.102.34.22:3306/magicapi?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


